// ============================================================
//  EDIT THIS FILE to change any content on the site.
//  Add / remove items in any array — the UI updates itself.
// ============================================================

export const profile = {
  name: "John Andrei Martinez",
  role: "AI/ML Engineer",
  tagline:
    "Computer Science student building AI/ML systems end-to-end — from local AI agents and RAG to forecasting and computer vision — and shipping them to production.",
  location: "San Jose del Monte, Bulacan",
  email: "martinezjandrei8425@gmail.com",
  links: [
    { label: "GitHub", url: "https://github.com/Zeref538" },
    { label: "LinkedIn", url: "https://linkedin.com/in/john-andrei-martinez-499a0b343" },
  ],
  about: [
    "I'm a Computer Science student at Our Lady of Fatima University working across AI/ML — and I care about shipping complete systems, not just training models in a notebook.",
    "My work spans agentic AI, RAG, forecasting, computer vision, and full-stack products: a fully local data-cleaning agent where the LLM never sees a raw row, an AI contract-screening system, a Philippine air-quality forecaster, an AI resort concierge with live Stripe booking, and the chatbot you're talking to right now. I own the whole pipeline — data, modeling, evaluation, and deployment.",
    "I'm looking for internship and entry-level roles in AI / ML Engineering or Data Analytics, where I can ship real systems, take on hard problems, and keep leveling up fast.",
  ],
};

export const experience = [
  {
    role: "ML Engineering Intern",
    company: "FlyRank AI",
    period: "Jun 2026 — Present",
    location: "Remote",
    bullets: [
      "Built a content refresh-priority scorer on real client search data — a hand-written rule first, then models, both judged on the same held-out clients.",
      "Queried a 9.8M-row monthly partition of the search warehouse in DuckDB and wrote the data contract: eligibility gate, feature list, and the leakage columns that are banned as features.",
      "Caught a label leak in my own work: adding a label-derived feature lifted ROC-AUC from 0.612 to 0.737. Removed it and kept the honest number.",
      "Showed the baseline's Precision@50 swings between 0.76 and 0.92 purely on tie-breaking — so a model's 0.88 vs 0.86 'win' is inside the noise, and reported it that way.",
    ],
  },
  {
    role: "Freelance Virtual Assistant",
    company: "Self-employed",
    period: "2025 — 2026",
    location: "Remote",
    bullets: [
      "Sourced and screened candidates via Indeed, streamlining HR recruitment workflows and reducing time-to-hire.",
      "Managed data encoding and digital filing, improving record accuracy and retrieval speed.",
      "Produced graphics and short-form video content, maintaining consistent brand identity across platforms.",
    ],
  },
];

export const projects = [
  {
    title: "callback-ai — Adaptive Interview Simulator Agent",
    groups: ["Agentic AI", "Full-Stack"],
    description:
      "An agentic interview simulator that decides what to ask you next based on how you just answered, then grades every claim against your own words. The session engine is a state-driven loop, not a script: each turn it re-reads remaining question budget, per-competency uncertainty, and your last answer, then chooses whether to probe deeper, switch competency, or write the report. Three interviewer personas change how hard you're pushed but never how you're graded. An evidence gate rejects any score whose supporting quote can't be found verbatim in your transcript, and weak competencies persist across sessions so the next run targets them.",
    tags: ["Agentic AI", "NVIDIA NIM", "Voice AI", "FastAPI", "Python"],
    metric: "ρ 0.81 grading · 0.0 variance",
    category: "Agentic AI · Evaluation · Full-Stack",
    date: "2026",
    image: "/projects/callback-1.jpg",
    images: [
      "/projects/callback-1.jpg",
      "/projects/callback-2.jpg",
      "/projects/callback-3.jpg",
      "/projects/callback-4.jpg",
      "/projects/callback-5.jpg",
    ],
    link: "https://github.com/Zeref538/callback-ai",
    demo: "https://callback-ai.onrender.com",
    highlights: [
      "Agent, not pipeline: a state-driven loop decides whether to probe, which competency to ask next, and when to stop — budget reallocated by weight × uncertainty after every answer",
      "Evidence gate: every score must quote your transcript verbatim; an unquotable score is rejected and regenerated, never shown",
      "Published eval on a live model (NVIDIA NIM, Llama 3.1): 0.81 ranking correlation, 0.0 grading variance across 5 re-grades, 1.0/0.0 probe precision",
    ],
  },
  {
    title: "Alfred — Multimodal AI Butler for Your PC",
    groups: ["Agentic AI"],
    description:
      "Local multimodal agent for Windows that actually acts on the machine — summoned by text, voice, global hotkey, or a webcam stop-gesture. A local LLM (Ollama, structured outputs at temperature 0) plans over a frozen 12-action service menu; a deterministic validator is the single door between anything untrusted and the OS. Consent tiers gate every act, an append-only ledger records them, and 'Alfred, stop' aborts mid-plan. Speech runs through local whisper plus a two-layer mishear corrector, and nothing executes until you confirm the exact plan Alfred reads back in a local British voice.",
    tags: ["Agentic AI", "Multimodal", "Voice AI", "Ollama", "Computer Vision", "Python"],
    metric: "4 input modes · 12 gated actions",
    category: "Agentic AI · Multimodal · Privacy",
    date: "2026",
    image: "/projects/alfred-demo.gif",
    images: [
      "/projects/alfred-demo.gif",
      "/projects/alfred-3.jpg",
      "/projects/alfred-12.jpg",
      "/projects/alfred-22.jpg",
    ],
    link: "https://github.com/Zeref538/alfred",
    demo: "https://zeref538.github.io/alfred/demo/",
    highlights: [
      "Four input modes — text, local whisper voice, global hotkey, opt-in webcam motion (which can only abort, never command) — all funnel through one validator → consent gate → executor path",
      "Safety by construction: typed action registry (no keystrokes or shell), per-action argument policy, tiered consent, snapshot-backed undo, and an append-only JSONL ledger that expires after 30 days",
      "Fully local and offline-capable: Ollama planner, whisper STT, Piper TTS — 102 tests, with a sealed 50-command evaluation frozen before any prompt existed",
    ],
  },
  {
    title: "Refusal Calibration LLM Fine-Tuning",
    groups: ["LLM Engineering"],
    description:
      "Fine-tuned a small free model to admit \"I don't know\" instead of making up confident wrong answers — without overcorrecting into a model that refuses everything. The catch: any model can stop making things up by simply refusing every question, so I measured both mistakes at once — how often it invents answers vs. how often it wrongly refuses — on the same fixed test set. Trained 15 versions and scored 19 setups; the honest takeaways matter more than any single score, including that a tiny 1.5B model is just too small for the method, while a 3B model both makes up fewer answers and gets more right — a result I re-ran on a second random seed to confirm it held up.",
    tags: ["LLM Fine-Tuning", "LoRA", "PyTorch", "Model Evaluation", "Python"],
    metric: "3B result replicated · 19 setups scored",
    category: "Fine-Tuning · Evaluation · Honesty",
    date: "2026",
    image: "/projects/refusal-1.jpg",
    images: [
      "/projects/refusal-1.jpg",
      "/projects/refusal-2.jpg",
      "/projects/refusal-3.jpg",
      "/projects/refusal-4.jpg",
      "/projects/refusal-5.jpg",
      "/projects/refusal-6.jpg",
      "/projects/refusal-7.jpg",
      "/projects/refusal-8.jpg",
    ],
    link: "https://github.com/Zeref538/refusal-calibration-LLM-Fine-Tuning",
    demo: "https://zeref538.github.io/refusal-calibration-LLM-Fine-Tuning/",
    demoLabel: "case study",
    highlights: [
      "Measured both failure modes together — making things up vs. wrongly refusing — on a fixed test set, because a model that refuses everything looks perfect on one metric and useless on the other",
      "Ran the exact same recipe three times with different random seeds and got very different results — proof that some of the fine-tuning 'wins' were noise, not real improvement",
      "A 1.5B model was too small to learn this cleanly; a 3B model made up fewer answers AND got more questions right at the same time — and re-running it on a second seed reproduced that, with results 4-7x more stable than at 1.5B",
    ],
  },
  {
    title: "Munti — A Tiny LLM From Scratch",
    groups: ["LLM Engineering"],
    description:
      "Built a 12.5M-parameter language model from the ground up in pure PyTorch — the tokenizer, the attention, the training loop and the sampler, with no pretrained weights and no ready-made GPT class — then trained it on TinyStories for 44 minutes on a free Kaggle T4 to a val loss of 1.505, where it writes coherent multi-paragraph children's stories with working dialogue. Before spending a single GPU hour I proved the code correct by deliberately overfitting four fixed batches to zero loss, which is what separates 'my model is undertrained' from 'my causal mask is broken'. The ablation is the part I'd defend hardest: removing positional embeddings cost only ~0.04 nats when I had predicted word salad, so instead of publishing the number I probed it twice — shuffling the input tokens destroys that model, proving a causal decoder recovers position from prefix length on its own, and a second seed reproduced the gap while the two baselines landed 0.003 apart.",
    tags: ["PyTorch", "Transformers", "From Scratch", "BPE Tokenizer", "Kaggle", "Python"],
    metric: "12.5M params from scratch · val 1.505 in 44 min",
    category: "From Scratch · Transformers · Evaluation",
    date: "2026",
    image: "/projects/munti-1.jpg",
    images: [
      "/projects/munti-1.jpg",
      "/projects/munti-2.jpg",
      "/projects/munti-3.jpg",
      "/projects/munti-4.jpg",
      "/projects/munti-5.jpg",
    ],
    link: "https://github.com/Zeref538/munti",
    demo: "https://zeref538.github.io/munti/",
    demoLabel: "case study",
    highlights: [
      "Wrote the transformer by hand — multi-head causal attention, pre-LN residual blocks, weight-tied embeddings — and proved it correct on CPU in under a minute before touching a GPU, by overfitting four fixed batches to loss 0.0000 with 100% greedy recall",
      "Predicted that removing positional embeddings would produce word salad and was wrong — it cost ~0.04 nats — so I measured why: shuffling tokens sends that model from 1.543 to 9.729, a larger collapse than the baseline's, proving causal masking already leaks position via prefix length",
      "Replicated the ablation at a second seed rather than trusting one reading: the two baselines land 0.003 apart while the effect is ~0.04, so between-seed noise sits an order of magnitude below the result being claimed",
      "Honest can-do/can't-do grounded in real generations: it writes stories with consistent characters and dialogue, but answers \"What is the capital of France?\" with a story about Santa, and loses entity tracking even mid-success (\"He opened the box and found a box!\")",
    ],
  },
  {
    title: "Token-Optimization LLM Fine-Tuning",
    groups: ["LLM Engineering"],
    description:
      "Fine-tuned a free open-weights model (Qwen2.5-1.5B-Instruct) via LoRA to say the same thing in fewer tokens without giving up accuracy — four training runs on free Kaggle T4s, with accuracy and token count always reported together, because a shorter wrong answer is a failure, not a saving. Runs v1–v3 traded 18–24 accuracy points for ~70% fewer tokens; diagnosing why produced v4: self-distillation on the base model's own verified-correct reasoning, keeping only generations that already reached the right answer and trimming boilerplate rather than derivation.",
    tags: ["LLM Fine-Tuning", "LoRA", "Unsloth", "PyTorch", "Qwen2.5", "Python"],
    metric: "−17% tokens · accuracy within 5 pts",
    category: "Fine-Tuning · Model Efficiency · Evaluation",
    date: "2026",
    image: "/projects/lean-1.jpg",
    images: [
      "/projects/lean-1.jpg",
      "/projects/lean-2.jpg",
      "/projects/lean-3.jpg",
      "/projects/lean-4.jpg",
      "/projects/lean-5.jpg",
    ],
    link: "https://github.com/Zeref538/Token-Optimization-LLM-Fine_Tuning",
    demo: "https://zeref538.github.io/Token-Optimization-LLM-Fine_Tuning/",
    demoLabel: "case study",
    highlights: [
      "Self-distillation recipe: trained on the base model's own reasoning, filtered to the 77.3% of generations that were already correct — so output length still scales with problem difficulty",
      "Two hypotheses for v1–v3's accuracy cost tested and falsified by evidence (compressor deleting reasoning; line-joining format), and less training made it worse, not better",
      "Honest evaluation on a held-out GSM8K test split disjoint from training, reporting accuracy and mean output tokens together across all five models",
    ],
  },
  {
    title: "YODA — Your Offline Data Agent",
    groups: ["Agentic AI", "Full-Stack"],
    description:
      "Privacy-first, fully local data-cleaning agent for CSV / Excel / SQLite — the LLM never sees a single raw row and nothing leaves the machine. A pandas profiler produces a PII-redacted metadata profile; a local LLM (Ollama, qwen3.5:4b) plans repairs as strict JSON; a human approves each step; deterministic pandas executes with a full audit log; a verifier re-profiles to confirm. Benchmarked against 1,589 ground-truth labeled errors with a published false-fix rate, plus a 39-instruction plain-language benchmark and a local 'Mission Control' web UI.",
    tags: ["Agentic AI", "Ollama", "Python", "pandas", "FastAPI"],
    metric: "96.4% fix · 0.00% false-fix",
    category: "Agentic AI · Data Cleaning · Privacy",
    date: "2026",
    image: "/projects/yoda-1.jpg",
    images: [
      "/projects/yoda-1.jpg",
      "/projects/yoda-2.jpg",
      "/projects/yoda-3.jpg",
      "/projects/yoda-4.jpg",
      "/projects/yoda-5.jpg",
      "/projects/yoda-6.jpg",
      "/projects/yoda-7.jpg",
    ],
    link: "https://github.com/Zeref538/yoda",
    demo: "https://zeref538.github.io/yoda/demo/",
    highlights: [
      "AI plans, pandas executes: the LLM sees only a PII-redacted profile — a unit test proves no raw value reaches a prompt",
      "Ground-truth benchmark: 99.1% detection / 96.4% fix / 0.00% false-fix across 1,589 labeled errors (vs rule-based baseline)",
      "Human-in-the-loop gate, JSONL audit log, recipes, data contracts, and a WebAssembly browser demo — runs with Wi-Fi off",
    ],
  },
  {
    title: "Aegix AI — Contract Compliance Screening",
    groups: ["RAG", "Full-Stack"],
    description:
      "RAG system that screens Philippine employment contracts against the Labor Code, grading every clause Compliant / Non-compliant / Vague / Missing with a statutory citation and plain-English reason. Contracts are segmented and judged by two LangChain LCEL chains with structured output, over a MongoDB Atlas vector-search knowledge base of curated statute rules. Verdicts stream live via Server-Sent Events as parallel workers finish.",
    tags: ["RAG", "LangChain", "Azure OpenAI", "Vector Search", "FastAPI"],
    metric: "84.5% verdict accuracy",
    category: "AI · RAG · Full-Stack",
    date: "2026",
    image: "/projects/aegix-1.jpg",
    images: ["/projects/aegix-1.jpg", "/projects/aegix-2.jpg", "/projects/aegix-3.jpg"],
    link: "https://github.com/Zeref538/aegix-ai",
    demo: "https://aegix-ai-zeref.vercel.app",
    highlights: [
      "RAG pipeline: LangChain LCEL + structured output over MongoDB Atlas $vectorSearch",
      "Live SSE streaming — parallel clause workers cut a 9-clause run ~128s → ~62s",
      "Evaluated on 18 labeled contracts: 100% recall, 94.8% citation accuracy",
    ],
  },
  {
    title: "Hangin' — PH Air-Quality Forecasting Dashboard",
    groups: ["ML & Forecasting", "Full-Stack"],
    description:
      "Forecasts PM2.5 for Philippine cities 1–24 hours ahead and translates it into plain-language health advice — unlike existing PH trackers that only show the current reading. One pooled scikit-learn model (HistGradientBoosting) across 5 metros, trained on ~1.9 years of free Open-Meteo air-quality + weather history, backtested honestly against a naive persistence baseline. A scheduled job re-fetches data and republishes live forecasts to an interactive React dashboard with a heatmap, AQI health gauge, and a model-performance panel.",
    tags: ["scikit-learn", "Time-Series", "Forecasting", "Python", "Open-Meteo", "React"],
    metric: "+15–23% MAE vs. naive",
    category: "ML · Forecasting · Dashboard",
    date: "2026",
    image: "/projects/hangin-1.jpg",
    images: ["/projects/hangin-1.jpg", "/projects/hangin-2.jpg", "/projects/hangin-3.jpg"],
    link: "https://github.com/Zeref538/hangin",
    demo: "https://hangin-zeref.vercel.app",
    highlights: [
      "Pooled HistGradientBoosting over 5 metros, ~1.9 yrs of free Open-Meteo data",
      "Honest backtest: beats naive persistence by +15–23% MAE at the 6–24h horizons",
      "Hourly GitHub Actions refresh republishes live 1/6/12/24h forecasts + EPA-AQI health advice",
    ],
  },
  {
    title: "ACRA — Adaptive Color Re-Encoding Algorithm",
    groups: ["ML & Forecasting", "Full-Stack"],
    description:
      "CNN-powered system that detects color-critical regions in public signage and re-encodes them for color vision deficiency without altering original design. Trained YOLOv8m on a custom 5-class dataset (33,774 annotated boxes) reaching 0.740 mAP50, and built the core re-encoding algorithm: CLAHE → CIELAB → Fuzzy C-Means → CIEDE2000 conflict detection → constrained optimization. Deployed via FastAPI + ONNX with Supabase (RLS, 24h auto-delete).",
    tags: ["YOLOv8", "Computer Vision", "ONNX", "FastAPI", "Supabase", "React"],
    metric: "0.740 mAP50",
    category: "Computer Vision · CNN · Data Annotation",
    date: "2025 — 2026",
    image: "/projects/acra.jpg",
    images: ["/projects/acra.jpg", "/projects/acra-2.jpg", "/projects/acra-3.jpg"],
    link: "",
    demo: "https://acra-sandy.vercel.app/dashboard",
    highlights: [
      "Trained YOLOv8m on 33,774 custom-annotated boxes → 0.740 mAP50",
      "Built the re-encoding core: CLAHE → CIELAB → Fuzzy C-Means → CIEDE2000",
      "Deployed FastAPI + ONNX inference with Supabase RLS & 24h auto-delete",
    ],
  },
  {
    title: "Solmara Resort & Villas — AI-Concierge Booking Platform",
    groups: ["RAG", "Full-Stack"],
    description:
      "A modern-luxury resort platform with Selene, a RAG concierge grounded in a curated knowledge base (rooms, rates, events, policies) via Azure OpenAI embeddings + chat, with an offline extractive fallback. Full booking flow with live availability, conflict detection (no double-booking), 15-minute payment holds, and Stripe Checkout (PHP). The concierge answers live availability questions straight from the booking system and doubles as a time-blocked itinerary planner.",
    tags: ["RAG", "Azure OpenAI", "Stripe", "React", "Node.js"],
    metric: "AI concierge + live booking",
    category: "RAG · AI Concierge · Full-Stack",
    date: "2026",
    image: "/projects/solmara-1.jpg",
    images: ["/projects/solmara-1.jpg", "/projects/solmara-2.jpg", "/projects/solmara-3.jpg"],
    link: "https://github.com/Zeref538/Solmara-Resort",
    demo: "https://solmara-resort-zeref.vercel.app",
    highlights: [
      "Selene RAG concierge: Azure OpenAI embeddings + chat over a curated KB, offline fallback",
      "Booking engine: live availability, conflict detection, 15-min payment holds, confirmation codes",
      "Stripe Checkout (PHP) with redirect verification + webhook; concierge answers live availability",
    ],
  },
  {
    title: "Portfolio — ML Terminal Website",
    groups: ["RAG", "Full-Stack"],
    description:
      "This site. A React + Vite portfolio with an 'ML terminal' personality — boot log, CRT scanlines, tmux-style status bar — plus zeref-bot: a RAG chatbot (Azure OpenAI gpt-5-mini) that embeds each question and retrieves over a vector index of the whole site — projects, READMEs, and a recruiter FAQ — through a rate-limited Vercel serverless function.",
    tags: ["RAG", "Azure OpenAI", "React", "Vite", "Vercel"],
    metric: "RAG chatbot",
    category: "RAG · AI Chatbot · Web",
    date: "2026",
    image: "/projects/portfolio.jpg",
    images: ["/projects/portfolio.jpg"],
    link: "https://github.com/Zeref538/portfolio",
    demo: "https://johnandrei.vercel.app",
    highlights: [
      "zeref-bot: RAG over an embedded index of the site (cosine retrieval, top-6 chunks), per-IP rate limited",
      "Terminal identity: boot log, CRT scanlines, session status bar",
      "Perf-tuned animations: rAF-throttled scroll effects, vendor chunk splitting",
    ],
  },
  {
    title: "CafèSync — Smart Coffee Shop Operations",
    groups: ["ML & Forecasting", "Full-Stack"],
    description:
      "Centralized coffee shop management for orders, inventory, and sales analytics. Node.js backend synced live via Firebase Firestore (zero-refresh multi-screen updates), PayMongo payments, and a Python AI insights layer generating operational alerts — ingredient reorder triggers and staffing recommendations from order-volume forecasting.",
    tags: ["Forecasting", "Python", "Firebase", "Node.js", "PayMongo"],
    metric: "Live multi-screen sync",
    category: "AI Insights · Realtime Sync · Full-Stack",
    date: "2025",
    image: "/projects/cafesync.jpg",
    images: ["/projects/cafesync.jpg", "/projects/cafesync-2.jpg", "/projects/cafesync-3.jpg"],
    link: "https://github.com/Zeref538/CafeSync",
    demo: "https://cafesync-3b25a.web.app/station/management",
    highlights: [
      "Zero-refresh multi-screen sync with Firestore realtime listeners",
      "Python AI insights: ingredient reorder triggers & staffing forecasts",
      "PayMongo payment integration with live sales analytics",
    ],
  },
  {
    title: "CLICKSILOG — Self-Ordering & Kitchen Display",
    groups: ["Full-Stack"],
    description:
      "Self-ordering and kitchen display system replacing manual order-taking. Built the order-routing logic linking customer orders to a real-time Kitchen Display System, integrated PayMongo for online payments, and automated inventory deduction on each order — keeping ordering, kitchen, and stock fully in sync.",
    tags: ["JavaScript", "Node.js", "Express", "REST APIs", "React"],
    metric: "End-to-end order sync",
    category: "Realtime Ordering · KDS · Payments",
    date: "2025",
    image: "/projects/clicksilog/menu.jpg",
    images: [
      "/projects/clicksilog/menu.jpg",
      "/projects/clicksilog/kds-2.jpg",
      "/projects/clicksilog/kds-3.jpg",
    ],
    link: "https://github.com/Zeref538/ClickSilog",
    demo: "",
    highlights: [
      "Order routing from customer screen to real-time Kitchen Display",
      "Automated inventory deduction on every confirmed order",
      "Role-based flows: Customer, Kitchen, Cashier, Admin",
    ],
  },
  {
    title: "Smart Scheduling System",
    groups: ["Full-Stack"],
    description:
      "Desktop class-scheduling platform in Java that auto-generates a conflict-free weekly timetable from courses, professors, rooms, and sections. A constraint-driven engine searches candidate day/time/room combinations and validates each against professor double-booking, room clashes, load balancing, and room optimization — with a live generation log and one-click CSV export.",
    tags: ["Algorithms", "Java 21", "MySQL", "Swing", "JDBC"],
    metric: "Conflict-free in seconds",
    category: "Constraint Solving · Algorithms · Desktop",
    date: "2025",
    image: "/projects/scheduler-1.jpg",
    images: ["/projects/scheduler-1.jpg", "/projects/scheduler-2.jpg", "/projects/scheduler-3.jpg"],
    link: "https://github.com/Zeref538/smart-scheduling-system",
    demo: "",
    highlights: [
      "Constraint engine: avoids professor, room & time-slot conflicts",
      "Configurable strategies — load balancing, room optimization, lunch breaks",
      "Interface-driven backend, SHA-256 auth, full CRUD over MySQL/JDBC",
    ],
  },
];

export const skills = [
  {
    group: "AI / Machine Learning",
    items: [
      "Python",
      "PyTorch",
      "TensorFlow",
      "scikit-learn",
      "LangChain",
      "RAG",
      "Agentic AI",
      "LLM Fine-Tuning",
      "Ollama",
      "NVIDIA NIM",
      "CNNs",
      "Hugging Face",
      "Kaggle",
    ],
  },
  {
    group: "Data",
    items: ["SQL", "PostgreSQL", "MongoDB", "Tableau", "Power BI"],
  },
  {
    group: "Engineering",
    items: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "FastAPI",
      "Docker",
      "Stripe",
      "Firebase",
      "Supabase",
    ],
  },
  {
    group: "Cloud & Tools",
    items: ["Azure", "Google Cloud", "Vercel", "Render", "Git", "GitHub", "Figma"],
  },
];

// url: public verify link (enables the "Verify Badge" button)
// image: badge artwork — save the PNG in public/certs/ with the filename below
export const certifications = [
  {
    name: "Claude 101",
    issuer: "Anthropic",
    year: "2026",
    url: "https://verify.skilljar.com/c/ggacokz4z57m",
    image: "/certs/claude-101.jpg",
  },
  {
    name: "Google AI Professional Certificate",
    issuer: "Google",
    year: "2026",
    url: "https://www.coursera.org/account/accomplishments/specialization/OVWHUIPY22YS",
    image: "/certs/google-ai-pro.jpeg",
  },
  {
    name: "Google Advanced Data Analytics Professional Certificate",
    issuer: "Google",
    year: "2026",
    url: "https://www.coursera.org/account/accomplishments/specialization/PW3PERYUBRH0",
    image: "/certs/advanced-data-analytics.jpeg",
  },
  {
    name: "Google Advanced Data Analytics Capstone",
    issuer: "Google",
    year: "2026",
    url: "https://www.coursera.org/account/accomplishments/verify/U7SVUTS082OA",
    image: "/certs/capstone-data-analytics.jpeg",
  },
  {
    name: "AWS AI Practitioner Challenge",
    issuer: "AWS",
    year: "2026",
    url: "https://www.udacity.com/certificate/e/4e7cbba8-2c4d-11f1-a1ae-434577b9e921",
    image: "/certs/aws-ai.png",
  },
  {
    name: "Cisco Certified Support Technician — Cybersecurity",
    issuer: "Cisco",
    year: "2026",
    url: "https://www.credly.com/badges/42e85a15-aaac-4481-8f59-9ee5e679ef00/linked_in_profile",
    image: "/certs/ccst-cybersecurity.png",
  },
  {
    name: "Oracle Cloud Infrastructure Certified AI Foundations Associate",
    issuer: "Oracle",
    year: "2025",
    url: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=016F034CEE51B778CA019B17844681C3281C47DC3872217B0B5C4FCC1017255F",
    image: "/certs/oci-ai-foundations.png",
  },
  {
    name: "Google Data Analytics Professional Certificate",
    issuer: "Google",
    year: "2025",
    url: "https://www.coursera.org/account/accomplishments/specialization/2HF46JKGRGU9",
    image: "/certs/data-analytics.jpeg",
  },
  {
    name: "Google Cybersecurity Professional Certificate",
    issuer: "Google",
    year: "2025",
    url: "https://www.coursera.org/account/accomplishments/professional-cert/certificate/Z09O6H72G4CX",
    image: "/certs/cybersecurity.jpg",
  },
  {
    name: "Building RAG Apps Using MongoDB",
    issuer: "MongoDB",
    year: "2026",
    url: "https://www.credly.com/badges/9c5941b9-a0c2-4736-926b-1a83aba0d210/public_url",
    image: "/certs/rag-mongodb.jpg",
  },
];

export const education = [
  {
    school: "Our Lady of Fatima University",
    degree: "BS Computer Science",
    period: "2023 — 2027",
    location: "",
    highlights: [
      "Dean's Lister 2023–2026",
      "Technical Member — English Society",
      "Member — Junior Philippines Computer Studies Directorate",
      "2nd Place — Python Programming Competition",
      "3rd Place — Database Designing Competition",
      "3rd Place — C Programming Competition",
    ],
  },
];
